# Generated by Django 5.2.9 on 2025-12-07 13:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mirror',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=128, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(default=8000)),
                ('public_key', models.TextField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('qr_token_hash', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('qr_url', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending User Scan'), ('active', 'Active'), ('ended', 'Ended')], default='pending', max_length=16)),
                ('mirror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mirrors.mirror')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('logs', models.JSONField(blank=True, default=list)),
                ('from_mirror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='mirrors.mirror')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mirrors.session')),
                ('to_mirror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='mirrors.mirror')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='videos/%Y/%m/%d/')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('codec', models.CharField(default='h264', max_length=64)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('encrypted', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='mirrors.session')),
            ],
        ),
    ]
