# Generated by Django 5.2.9 on 2025-12-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirrors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='device_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
