# Generated by Django 5.2.9 on 2025-12-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirrors', '0002_session_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_active',
        ),
    ]
