# Generated by Django 5.2.9 on 2025-12-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirrors', '0003_remove_session_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='export_used',
            field=models.BooleanField(default=False),
        ),
    ]
